config/routes.rb
Rails.application.routes.draw do

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  
  resources :sessions, only: [:index, :show, :destroy]
  resource  :password, only: [:edit, :update]
  
  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:show, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end
  
  namespace :authentications do
    resources :events, only: :index
  end
  
  resource :invitation, only: [:new, :create]

  resources :profiles, only: [ :index, :show, :edit, :update, :destroy]
  post "search_result", to: "profiles#search"
  get "building/units", to: "invitations#units"

  resources :buildings

  resources :units
  post "search_unit", to: "units#search_unit"

  namespace :access_management do
    resource :access_units, only: [:new, :create, :destroy]
    resource :access_buildings, only: [:new, :create, :destroy]
    resource :assign_units, only: [:new, :create, :destroy]
    resource :assign_buildings, only: [:new, :create, :destroy]
  end
  
  resource :access_management, only: [:create, :show, :destroy]
  get "unit_access", to: "access_managements#unit_access"
  get "building_access", to: "access_managements#building_access"

  get "unit/users", to: "buildings#unit_users"
  get "building/users", to: "buildings#building_users"

  get "home", to:"home#index"
  
end

app/models/building.rb
class Building < ApplicationRecord
    has_many :building_users
    has_many :users, through: :building_users
    has_many :units
    
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController

    before_action :set_building, except: [:new, :create, :index, :unit_users, :building_users]

    def new
        @building = Building.new
        set_manager_supervisor
    end


    def create
        @building = Building.new(building_params)

        if @building.save
            redirect_to buildings_path, notice: "Building has been created successfully"
        else
            render :new, status: :unprocessable_entity
        end
    end



    def update
        if @building.update(building_params)
            redirect_to buildings_path, notice: "Building information has been changed successfully"
        else
            render :edit, notice: "Building information has been changed successfully"
        end
    end


    def index
        @buildings = Building.all
    end

    def edit
        set_manager_supervisor
    end

    def destroy
        authorize [:admin, Current.user]

        if @building.destroy
            redirect_to buildings_path, notice: "Building has been deleted successfully"
          else
            render :index, alert: "Unable to delete the building"
          end
    end

    #these below action is for the stimulus to load building users and building unit user

    def unit_users
        @target = params[:target]
        unit = Unit.find(params[:bid])
        @users = unit.users
        @users_list = [["Select User", ""]]
        @users.each do |user|
            @users_list.push(["#{user.name}, #{user.email}", user.id])    
        end
        respond_to do |format|
          format.turbo_stream
        end
      end
    
      def building_users
        @target = params[:target]
        building = Building.find(params[:bid])
        @users = building.users
        @users_list = [["Select User", ""]]
        @users.each do |user|
            @users_list.push(["#{user.name}, #{user.email}", user.id])    
        end
        respond_to do |format|
          format.turbo_stream
        end
      end

    private

    def set_manager_supervisor
        @managers = User.search_by_roles("manager")
        @supervisors = User.search_by_roles("supervisor")
        @manager_list = [["Select a manager for the building", ""]]
        @supervisor_list = [["Select a supervisor for the building", ""]]

        @managers.each do |manager|
            @manager_list.push(["#{manager.name}, #{manager.email}", manager.id])    
        end

        @supervisors.each do |supervisor|
            @supervisor_list.push(["#{supervisor.name}, #{supervisor.email}", supervisor.id])    
        end
    end

    def set_building
        @building = Building.find(params[:id])
    end
    def building_params
        params.require(:building).permit( :name, :address, :building_manager, :building_supervisor )
    end

    
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/buildings/building_users.turbo_stream.erb
<%= turbo_stream.update @target do %>
    <%= options_for_select @users_list %>
<% end %>

app/views/buildings/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="mt-10">
    <div class="w-full p-4 bg-body-card border border-gray-200 rounded-lg shadow-2xl sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
      <%= form_with(url: building_path, model: @building) do |form| %>
        <h5 class="text-xl font-medium text-gray-900 dark:text-white mb-4">Edit a building</h5>
        <% if @building.errors.any? %>
          <div class="mb-10" style="color: red">
            <h2><%= pluralize(@building.errors.count, "error") %> prohibited this user from being saved:</h2>

            <ul>
              <% @building.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="relative z-0 w-full mb-8 group">
          <%= form.text_field :name, required: true, placeholder: "", autocomplete: "email", class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer dark:text-white dark:border-gray-600 dark:focus:border-blue-500" %>
          <%= form.label :name, class: "peer-focus:font-medium absolute text-sm text-gray-500 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>
        </div>

        <div class="relative z-0 w-full mb-5 group">
          <%= form.text_field :address, required: true,  placeholder: "", autocomplete: "email", class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer dark:text-white dark:border-gray-600 dark:focus:border-blue-500" %>
          <%= form.label :address, class: "peer-focus:font-medium absolute text-sm text-gray-500 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>
        </div>

        <div class="relative z-0 w-full mb-5 group">
            <%= form.select :building_manager, options_for_select(@manager_list, :selected => @building.building_manager), {}, { class: "mt-10 bg-body-card border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" } %>
        </div>
        
        <div class="relative z-0 w-full mb-5 group">
            <%= form.select :building_supervisor, options_for_select(@supervisor_list, :selected => @building.building_supervisor), {}, { class: "mt-10 bg-body-card border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" } %>
        </div>
        

        <div class="flex justify-between mt-12">
          <%= form.submit "Update", class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
          <%= link_to "Cancel", buildings_path, class: "text-black bg-body-card border border-gray-400 hover:bg-white focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:text-white dark:bg-gray-600 dark:border-gray-600 dark:hover:bg-gray-800 dark:focus:ring-gray-800 dark:hover:border-gray-600" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/buildings/index.html.erb
<div class="overflow-x-auto shadow-md sm:rounded-lg p-4">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
        <caption class="p-5 text-lg font-semibold text-left rtl:text-right text-gray-900 bg-white dark:text-white dark:bg-gray-800">
            All Buildings List
        </caption>
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3">
                    Name
                </th>
                <th scope="col" class="px-6 py-3">
                    Address
                </th>
                <th scope="col" class="px-6 py-3">
                    Building Manager
                </th>
                <th scope="col" class="px-6 py-3">
                    Building Supervisor
                </th>
                <th scope="col" class="px-6 py-3">
                </th>
            </tr>
        </thead>
        <tbody>
            <% @buildings.each_with_index do |building, index| %>
                <tr class="<%= index.odd? ? 'bg-gray-100 dark:bg-gray-700' : 'bg-white dark:bg-gray-800' %> border-b dark:border-gray-700">
                    <td class="px-6 py-4">
                        <%= building.name %>
                    </td>
                    <td class="px-6 py-4">
                        <%= building.address %>
                    </td>
                    <td class="px-6 py-4 font-medium text-blue-600 dark:text-blue-500 hover:underline">
                        <% manager = User.find_by(id: building.building_manager) %>
                        <%= link_to manager.name, profile_path(manager) if manager %>
                    </td>
                    <td class="px-6 py-4 font-medium text-blue-600 dark:text-blue-500 hover:underline">
                        <% supervisor = User.find_by(id: building.building_supervisor) %>
                        <%= link_to supervisor.name, profile_path(supervisor) if supervisor %>
                    </td>
                    <td class="text-center">
                        <div class="font-medium flex flex-row space-x-6 text-blue-600 dark:text-blue-500 hover:underline">
                            <div class="hover:underline">
                                <%= link_to "Edit", edit_building_path(building) %>
                            </div>
                            <% if policy([:admin, Current.user]).destroy? %>
                                <div class="hover:underline">
                                    <%= button_to "Delete", building_path(building), method: :delete, data: {turbo_confirm: "Are you sure you want to permanently delete this building ?" } %>
                                </div>
                            <% end %>
                        </div>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/buildings/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="mt-10">
    <div class="w-full p-4 bg-body-card border border-gray-200 rounded-lg shadow-2xl sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
      <%= form_with(url: buildings_path, model: @building) do |form| %>
        <h5 class="text-xl font-medium text-gray-900 dark:text-white mb-4">Create a building</h5>
        <% if @building.errors.any? %>
          <div class="mb-10" style="color: red">
            <h2><%= pluralize(@building.errors.count, "error") %> prohibited this user from being saved:</h2>

            <ul>
              <% @building.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="relative z-0 w-full mb-8 group">
          <%= form.text_field :name, required: true, placeholder: "", autocomplete: "email", class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer dark:text-white dark:border-gray-600 dark:focus:border-blue-500" %>
          <%= form.label :name, class: "peer-focus:font-medium absolute text-sm text-gray-500 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>
        </div>

        <div class="relative z-0 w-full mb-5 group">
          <%= form.text_field :address, required: true,  placeholder: "", autocomplete: "email", class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer dark:text-white dark:border-gray-600 dark:focus:border-blue-500" %>
          <%= form.label :address, class: "peer-focus:font-medium absolute text-sm text-gray-500 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>
        </div>

        <div class="relative z-0 w-full mb-5 group">
            <%= form.select :building_manager, options_for_select(@manager_list, :selected => params[:building_manager]), {}, { class: "mt-10 bg-body-card border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" } %>
        </div>
        
        <div class="relative z-0 w-full mb-5 group">
            <%= form.select :building_supervisor, options_for_select(@supervisor_list, :selected => params[:building_supervisor]), {}, { class: "mt-10 bg-body-card border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" } %>
        </div>
        

        <div class="flex justify-between mt-12">
          <%= form.submit "Create", class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
          <%= link_to "Cancel", home_path, class: "text-black bg-body-card border border-gray-400 hover:bg-white focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:text-white dark:bg-gray-600 dark:border-gray-600 dark:hover:bg-gray-800 dark:focus:ring-gray-800 dark:hover:border-gray-600" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/buildings/unit_users.turbo_stream.erb
<%= turbo_stream.update @target do %>
    <%= options_for_select @users_list %>
<% end %>